title: "Evolution of Mosquito-Borne Diseases in Latin America 2015-2"
description: "Dataset on the evolution of mosquito-borne diseases in Latin America and the Caribbean 2015-2024. Includes data on Dengue, Zika, Chikungunya, and Mala"
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/evolution-of-mosquito-borne-diseases-in-latin-america-2015-2024-database-by-coun"
